[project]
name = "quokka-sharp-root"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["quokka-sharp"]

[tool.uv.sources]
quokka-sharp = { path = "quokka_sharp", editable = true }

[tool.ruff.format]
exclude = [
  "*.md",
  "quokka_sharp/quokka_sharp/encoding/comput2cnf.py",
  "quokka_sharp/quokka_sharp/encoding/pauli2cnf.py",
]

[dependency-groups]
dev = ["pytest>=9.1.1", "ruff>=0.16.9"]
